# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import socialage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date_liked')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(blank=True, default=socialage.models.char_uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='NAME_NOT_FOUND', max_length=100)),
                ('fb_id', models.CharField(default='FACEBOOK_PAGE_NOT_FOUND', max_length=30)),
                ('tw_id', models.CharField(max_length=30)),
                ('fb_handle', models.CharField(default='FACEBOOK_PAGE_NOT_FOUND', max_length=100)),
                ('tw_handle', models.CharField(max_length=100)),
                ('ageUnder12', models.FloatField(default=0)),
                ('age12to13', models.FloatField(default=0)),
                ('age14to15', models.FloatField(default=0)),
                ('age16to17', models.FloatField(default=0)),
                ('age18to24', models.FloatField(default=0)),
                ('age25to34', models.FloatField(default=0)),
                ('age35to44', models.FloatField(default=0)),
                ('age45to54', models.FloatField(default=0)),
                ('age55to64', models.FloatField(default=0)),
                ('ageAbove65', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='socialage.Page')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(blank=True, default=socialage.models.char_uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fb_id', models.CharField(max_length=60)),
                ('tw_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='twitterfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_pages', to='socialage.User'),
        ),
        migrations.AddField(
            model_name='facebookpagelike',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialage.Page'),
        ),
        migrations.AddField(
            model_name='facebookpagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_pages', to='socialage.User'),
        ),
    ]
